ФБ-24 Тихонова Анастасія Лабораторна робота 4

Перший рівень

In [18]:
import csv

def to_csv():
    txt_file = 'D:/anaconda3/envs/lab4/household_power_consumption.txt'
    csv_file = 'household_power_consumption.csv'

    with open(txt_file, 'r') as file_in, open(csv_file, 'w', newline='') as file_out:
        reader = csv.reader(file_in, delimiter=';')
        writer = csv.writer(file_out)

        for row in reader:
            writer.writerow(row)
    print(f"Успішно конвертовано {txt_file} у {csv_file}")
to_csv()

Успішно конвертовано D:/anaconda3/envs/lab4/household_power_consumption.txt у household_power_consumption.csv

In [58]:
import pandas as pd
import numpy as np
from datetime import time as dt_time

file = "household_power_consumption.csv"

def pd_df():

    file = "household_power_consumption.csv"
    dtype = {
        'Global_active_power': float,
        'Global_reactive_power': float,
        'Voltage': float,
        'Global_intensity': float,
        'Sub_metering_1': float,
        'Sub_metering_2': float,
        'Sub_metering_3': float
    }

    na_values = ['?']
    df = pd.read_csv(file, dtype=dtype, na_values=na_values)

    df["Date"] = pd.to_datetime(df["Date"], dayfirst=True)
    df["Time"] = pd.to_datetime(df["Time"], format='%H:%M:%S').dt.time
    df = df.drop(df.loc[(df["Sub_metering_1"] == 0) & (df["Sub_metering_2"] == 0) & (df["Sub_metering_3"] == 0)].index).dropna()
    return df
pd_df()

df = pd_df()

1. Обрати всі домогосподарства, у яких загальна активна споживана потужність перевищує 5 кВт.

In [59]:
def filter_by_power(df):
    filtered_df = df[df['Global_active_power'] > 5.0]
    return filtered_df
filter_by_power(df)

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
1,2006-12-16,17:25:00,5.360,0.436,233.63,23.0,0.0,1.0,16.0
2,2006-12-16,17:26:00,5.374,0.498,233.29,23.0,0.0,2.0,17.0
3,2006-12-16,17:27:00,5.388,0.502,233.74,23.0,0.0,1.0,17.0
11,2006-12-16,17:35:00,5.412,0.470,232.78,23.2,0.0,1.0,17.0
12,2006-12-16,17:36:00,5.224,0.478,232.99,22.4,0.0,1.0,16.0
...,...,...,...,...,...,...,...,...,...
2069356,2010-11-22,18:40:00,5.408,0.150,231.50,23.6,48.0,0.0,0.0
2069357,2010-11-22,18:41:00,5.528,0.144,232.48,24.6,53.0,0.0,0.0
2071586,2010-11-24,07:50:00,5.172,0.050,235.18,22.0,0.0,38.0,17.0
2071587,2010-11-24,07:51:00,5.750,0.000,234.40,24.6,0.0,39.0,17.0
2072997,2010-11-25,07:21:00,5.074,0.240,238.55,21.4,1.0,2.0,18.0

2. Обрати всі домогосподарства, у яких вольтаж перевищує 235 В.

In [60]:
def filter_by_voltage(df):
    filtered_df = df[df['Voltage'] > 235]
    return filtered_df
filter_by_voltage(df)

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
4,2006-12-16,17:28:00,3.666,0.528,235.68,15.8,0.0,1.0,17.0
5,2006-12-16,17:29:00,3.520,0.522,235.02,15.0,0.0,2.0,17.0
6,2006-12-16,17:30:00,3.702,0.520,235.09,15.8,0.0,1.0,17.0
7,2006-12-16,17:31:00,3.700,0.520,235.22,15.8,0.0,1.0,17.0
14,2006-12-16,17:38:00,4.054,0.422,235.24,17.6,0.0,1.0,17.0
...,...,...,...,...,...,...,...,...,...
2075243,2010-11-26,20:47:00,0.910,0.000,238.71,3.8,0.0,1.0,0.0
2075244,2010-11-26,20:48:00,0.912,0.000,239.25,3.8,0.0,1.0,0.0
2075245,2010-11-26,20:49:00,0.948,0.000,238.16,4.0,0.0,1.0,0.0
2075246,2010-11-26,20:50:00,1.198,0.128,238.11,5.0,0.0,1.0,0.0
2075247,2010-11-26,20:51:00,1.024,0.106,238.84,4.2,0.0,1.0,0.0

3. Обрати всі домогосподарства, у яких сила струму лежить в межах 19-20 А, для них виявити ті, у яких пральна машина та холодильних споживають більше, ніж бойлер та кондиціонер.

In [61]:
def filter_by_current_and_consumption(df):
    filtered_df = df[(df['Global_intensity'] >= 19) & (df['Global_intensity'] <= 20)]
    filtered_df = filtered_df[(filtered_df['Sub_metering_2'] > filtered_df['Sub_metering_3'])] 
    return filtered_df

filter_by_current_and_consumption(df)

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
45,2006-12-16,18:09:00,4.464,0.136,234.66,19.0,0.0,37.0,16.0
460,2006-12-17,01:04:00,4.582,0.258,238.08,19.6,0.0,13.0,0.0
464,2006-12-17,01:08:00,4.618,0.104,239.61,19.6,0.0,27.0,0.0
475,2006-12-17,01:19:00,4.636,0.140,237.37,19.4,0.0,36.0,0.0
476,2006-12-17,01:20:00,4.634,0.152,237.17,19.4,0.0,35.0,0.0
...,...,...,...,...,...,...,...,...,...
2071589,2010-11-24,07:53:00,4.666,0.000,235.72,19.8,0.0,39.0,17.0
2071590,2010-11-24,07:54:00,4.694,0.000,236.78,19.8,0.0,39.0,18.0
2071591,2010-11-24,07:55:00,4.602,0.000,237.08,19.4,0.0,40.0,17.0
2071592,2010-11-24,07:56:00,4.536,0.000,237.03,19.0,0.0,39.0,17.0
2071593,2010-11-24,07:57:00,4.626,0.000,236.78,19.4,0.0,39.0,17.0

4. Обрати випадковим чином 500000 домогосподарств (без повторів елементів вибірки), для них обчислити середні величини усіх 3-х груп споживання електричної енергії,

In [62]:
def random_sample_average(df, n=500000):
    sampled_df = df.sample(n=n, replace=False)
    averages = sampled_df[['Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3']].mean()
    return averages
random_sample_average(df, n=500000)

Sub_metering_1    1.563734
Sub_metering_2    1.828034
Sub_metering_3    9.106402
dtype: float64

5. Обрати ті домогосподарства, які після 18-00 споживають понад 6 кВт за хвилину в середньому, серед відібраних визначити ті, у яких основне споживання електроенергії у вказаний проміжок часу припадає на пральну машину, сушарку, холодильник та освітлення (група 2 є найбільшою), а потім обрати кожен третій результат із першої половини та кожен четвертий результат із другої половини.

In [63]:
def complex_filter(df):
    filtered_df = df[(df['Time'].apply(lambda x: x > dt_time(hour=18))) & (df['Global_active_power'] > 6.0)]
    filtered_df = filtered_df[(filtered_df['Sub_metering_2'] > filtered_df['Sub_metering_1']) &
                              (filtered_df['Sub_metering_2'] > filtered_df['Sub_metering_3']) &
                              (filtered_df['Sub_metering_2'] > filtered_df['Sub_metering_2'].mean())]
    first_half = filtered_df.head(len(filtered_df) // 2)
    second_half = filtered_df.tail(len(filtered_df) // 2)
    result = pd.concat([first_half.iloc[::3, :], second_half.iloc[::4, :]])
    return result
complex_filter(df)

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
41,2006-12-16,18:05:00,6.052,0.192,232.93,26.2,0.0,37.0,17.0
44,2006-12-16,18:08:00,6.308,0.116,232.25,27.0,0.0,36.0,17.0
17496,2006-12-28,21:00:00,6.376,0.252,235.94,27.4,1.0,53.0,17.0
17499,2006-12-28,21:03:00,7.906,0.286,235.93,33.6,1.0,73.0,17.0
17502,2006-12-28,21:06:00,7.184,0.000,235.70,30.4,2.0,73.0,17.0
...,...,...,...,...,...,...,...,...,...
2066467,2010-11-20,18:31:00,6.830,0.394,229.39,30.2,24.0,34.0,16.0
2066471,2010-11-20,18:35:00,6.784,0.364,228.38,30.0,21.0,35.0,16.0
2066475,2010-11-20,18:39:00,6.362,0.372,229.83,28.0,16.0,35.0,16.0
2066479,2010-11-20,18:43:00,6.324,0.376,229.93,27.8,14.0,35.0,17.0
2066485,2010-11-20,18:49:00,6.210,0.174,228.82,27.4,21.0,34.0,17.0

Виконання завдань з використанням NumPy

Конвертація файлу

In [2]:
import numpy as np

def to_csv():
    txt_file = 'D:/anaconda3/envs/lab4/household_power_consumption.txt'
    csv_file = 'household_power_consumption_np.csv'

    data = np.genfromtxt(txt_file, delimiter=';', dtype=None, encoding=None)

    np.savetxt(csv_file, data, delimiter=',', fmt='%s')

    print(f"Успішно конвертовано {txt_file} у {csv_file}")
to_csv()

Успішно конвертовано D:/anaconda3/envs/lab4/household_power_consumption.txt у household_power_consumption_np.csv

Поборотися зі зниклими даними

In [2]:
import numpy as np
def file_to_array(file_path):
    return np.genfromtxt(file_path, delimiter=',', dtype=None, names=True, encoding=None)

file_path = "household_power_consumption_np.csv"
data_array = file_to_array(file_path)

In [39]:
import numpy as np
from datetime import time as dt_time

def np_df(file):

    data = np.genfromtxt(file, delimiter=',', dtype=str, skip_header=1)
    data = data[~np.any(data == '?', axis=1)]

    dates_column = data[:, 0]   

    dates_datetime = []
    for date_str in dates_column:
        day, month, year = map(int, date_str.split('/'))
        date_obj = np.datetime64(f"{year:04d}-{month:02d}-{day:02d}")
        dates_datetime.append(date_obj)
    dates_datetime = np.array(dates_datetime)

    numeric_columns = [2, 3, 4, 5, 6, 7, 8]
    #data[:, numeric_columns] = data[:, numeric_columns].astype(float)

    for i in numeric_columns:
        data[:, i] = np.array(data[:, i], dtype=float)

        
    return data

file = "household_power_consumption_np.csv"
numeric_columns = [2, 3, 4, 5, 6, 7, 8]
data = np_df(file)
print(data[:5])

[['16/12/2006' '17:24:00' '4.216' '0.418' '234.84' '18.4' '0.0' '1.0'
  '17.0']
 ['16/12/2006' '17:25:00' '5.36' '0.436' '233.63' '23.0' '0.0' '1.0'
  '16.0']
 ['16/12/2006' '17:26:00' '5.374' '0.498' '233.29' '23.0' '0.0' '2.0'
  '17.0']
 ['16/12/2006' '17:27:00' '5.388' '0.502' '233.74' '23.0' '0.0' '1.0'
  '17.0']
 ['16/12/2006' '17:28:00' '3.666' '0.528' '235.68' '15.8' '0.0' '1.0'
  '17.0']]

1. Обрати всі домогосподарства, у яких загальна активна споживана потужність перевищує 5 кВт.

In [40]:
def filter_by_power_np(data):
    global_active_power = data[:, 2].astype(float)
    
    filtered_indices = np.where(global_active_power > 5.0)
    filt_data = data[filtered_indices]
    
    return filt_data

filter_by_power_np(data)

array([['16/12/2006', '17:25:00', '5.36', ..., '0.0', '1.0', '16.0'],
       ['16/12/2006', '17:26:00', '5.374', ..., '0.0', '2.0', '17.0'],
       ['16/12/2006', '17:27:00', '5.388', ..., '0.0', '1.0', '17.0'],
       ...,
       ['24/11/2010', '07:50:00', '5.172', ..., '0.0', '38.0', '17.0'],
       ['24/11/2010', '07:51:00', '5.75', ..., '0.0', '39.0', '17.0'],
       ['25/11/2010', '07:21:00', '5.074', ..., '1.0', '2.0', '18.0']],
      dtype='<U10')

2. Обрати всі домогосподарства, у яких вольтаж перевищую 235 В.

In [43]:
def filter_by_voltage_np(data):
    voltage = data[:, 4].astype(float)

    filtered_voltage = np.where(voltage > 235.0)
    volt_data = voltage[filtered_voltage]
    
    return volt_data

print(filter_by_voltage_np(data))

[235.68 235.02 235.09 ... 239.82 239.7  239.55]

3. Обрати всі домогосподарства, у яких сила струму лежить в межах 19-20 А, для них виявити ті, у яких пральна машина та холодильних споживають більше, ніж бойлер та кондиціонер.

In [50]:
def filter_by_current_and_consumption_np(data):
    filtered_data = data[(data[:, 5].astype(float) >= 19) & (data[:, 5].astype(float) <= 20)]
    print(filtered_data)
    filtered_data = data[(data[:, 7].astype(float) > (data[:, 8].astype(float))) &
                    (data[:, 7].astype(float) > (data[:, 6].astype(float)))]
    return filtered_data
    print(filtered_data)


filter_by_current_and_consumption_np(data)

[['16/12/2006' '17:34:00' '4.448' ... '0.0' '1.0' '17.0']
 ['16/12/2006' '17:48:00' '4.474' ... '0.0' '0.0' '17.0']
 ['16/12/2006' '17:57:00' '4.512' ... '0.0' '0.0' '17.0']
 ...
 ['24/11/2010' '07:55:00' '4.602' ... '0.0' '40.0' '17.0']
 ['24/11/2010' '07:56:00' '4.536' ... '0.0' '39.0' '17.0']
 ['24/11/2010' '07:57:00' '4.626' ... '0.0' '39.0' '17.0']]

array([['16/12/2006', '18:04:00', '4.928', ..., '0.0', '37.0', '16.0'],
       ['16/12/2006', '18:05:00', '6.052', ..., '0.0', '37.0', '17.0'],
       ['16/12/2006', '18:06:00', '6.752', ..., '0.0', '36.0', '17.0'],
       ...,
       ['26/11/2010', '20:49:00', '0.948', ..., '0.0', '1.0', '0.0'],
       ['26/11/2010', '20:50:00', '1.198', ..., '0.0', '1.0', '0.0'],
       ['26/11/2010', '20:51:00', '1.024', ..., '0.0', '1.0', '0.0']],
      dtype='<U10')

4. Обрати випадковим чином 500000 домогосподарств (без повторів елементів вибірки), для них обчислити середні величини усіх 3-х груп споживання електричної енергії,

In [51]:
def random_sample_average_np(data, n=500000):
    sampled_indices = np.random.choice(data.shape[0], n, replace=False)

    sampled_data = data[sampled_indices, :]
    
    sub_metering_1 = sampled_data[:, 6].astype(float)
    sub_metering_2 = sampled_data[:, 7].astype(float)
    sub_metering_3 = sampled_data[:, 8].astype(float)
    
    averages = np.mean([sub_metering_1, sub_metering_2, sub_metering_3], axis=1)
    
    return averages

averages = random_sample_average_np(data, n=500000)
print(averages)

[1.132248 1.294764 6.447622]

5. Обрати ті домогосподарства, які після 18-00 споживають понад 6 кВт за хвилину в середньому, серед відібраних визначити ті, у яких основне споживання електроенергії у вказаний проміжок часу припадає на пральну машину, сушарку, холодильник та освітлення (група 2 є найбільшою), а потім обрати кожен третій результат із першої половини та кожен четвертий результат із другої половини.

In [67]:
def complex_filter_np(data):
    time_column = 1
    power_column = 2
    sub_metering_1_column = 6
    sub_metering_2_column = 7
    sub_metering_3_column = 8

    times = np.array([t.split(':') for t in data[:, time_column]], dtype=int)
    after_18_indices = times[:, 0] >= 18
    filtered_data = data[after_18_indices]

    global_active_power = filtered_data[:, power_column].astype(float)
    high_power_indices = global_active_power > 6.0
    filtered_data = filtered_data[high_power_indices]

    sub_metering_1 = filtered_data[:, sub_metering_1_column].astype(float)
    sub_metering_2 = filtered_data[:, sub_metering_2_column].astype(float)
    sub_metering_3 = filtered_data[:, sub_metering_3_column].astype(float)

    dominant_group_2_indices = (sub_metering_2 > sub_metering_1) & (sub_metering_2 > sub_metering_3) & (sub_metering_2 > sub_metering_2.mean())
    filtered_data = filtered_data[dominant_group_2_indices]

    mid_index = len(filtered_data) // 2
    first_half = filtered_data[:mid_index]
    second_half = filtered_data[mid_index:]

    first_half_result = first_half[::3]
    second_half_result = second_half[::4]

    result = np.vstack((first_half_result, second_half_result))

    return result

filtered_data = complex_filter_np(data)
print(filtered_data)

[['16/12/2006' '18:05:00' '6.052' ... '0.0' '37.0' '17.0']
 ['16/12/2006' '18:08:00' '6.308' ... '0.0' '36.0' '17.0']
 ['28/12/2006' '21:00:00' '6.376' ... '1.0' '53.0' '17.0']
 ...
 ['20/11/2010' '18:37:00' '6.31' ... '15.0' '35.0' '16.0']
 ['20/11/2010' '18:41:00' '6.282' ... '14.0' '35.0' '16.0']
 ['20/11/2010' '18:45:00' '6.564' ... '13.0' '40.0' '16.0']]

Обчислення часових витрат на виконання процедур

In [69]:
import time

def main():
    print("\nЗавдання 1")
    start_time = time.time()
    filtered_df = filter_by_power(df)
    print(filtered_df)
    end_time = time.time() - start_time

    print("\nЗавдання 1 (з використанням NumPy)")
    start_time_np = time.time()
    filtered_df = filter_by_power_np(data)
    print(filtered_df)
    end_time_np = time.time() - start_time_np
    print(f"Час виконання:\nPd: {end_time} Np:{end_time_np} сек\n ------------------------------------------ \n")

    print("\nЗавдання 2")
    start_time = time.time()
    filtered_df = filter_by_voltage(df)
    print(filtered_df)
    end_time = time.time() - start_time

    print("\nЗавдання 2 (з використанням NumPy)")
    start_time_np = time.time()
    filtered_df = filter_by_voltage_np(data)
    print(filtered_df)
    end_time_np = time.time() - start_time_np
    print(f"Час виконання:\nPd: {end_time} Np:{end_time_np} сек\n ------------------------------------------ \n")

    print("\nЗавдання 3")
    start_time = time.time()
    filtered_df = filter_by_current_and_consumption(df)
    print(filtered_df)
    end_time = time.time() - start_time

    print("\nЗавдання 3 (з використанням NumPy)")
    start_time_np = time.time()
    filtered_df = filter_by_current_and_consumption_np(data)
    print(filtered_df)
    end_time_np = time.time() - start_time_np
    print(f"Час виконання:\nPd: {end_time} Np:{end_time_np} сек\n ------------------------------------------ \n")

    print("\nЗавдання 4")
    start_time = time.time()
    averages = random_sample_average(df, n=500000)
    print(averages)
    end_time = time.time() - start_time

    print("\nЗавдання 4 (з використанням NumPy)")
    start_time_np = time.time()
    averages = random_sample_average_np(data, n=500000)
    print(averages)
    end_time_np = time.time() - start_time_np
    print(f"Час виконання:\nPd: {end_time} Np:{end_time_np} сек\n ------------------------------------------ \n")

    print("\nЗавдання 5:")
    start_time = time.time()
    filtered_df = complex_filter(df)
    print(filtered_df)
    end_time = time.time() - start_time

    print("\nЗавдання 5 (з використанням NumPy)")
    start_time_np = time.time()
    filtered_df = complex_filter_np(data)
    print(filtered_df)
    end_time_np = time.time() - start_time_np
    print(f"Час виконання:\nPd: {end_time} Np:{end_time_np} сек\n ------------------------------------------ \n")

if __name__ == "__main__":
    main()

Завдання 1
              Date      Time  Global_active_power  Global_reactive_power  \
1       2006-12-16  17:25:00                5.360                  0.436
2       2006-12-16  17:26:00                5.374                  0.498
3       2006-12-16  17:27:00                5.388                  0.502
11      2006-12-16  17:35:00                5.412                  0.470
12      2006-12-16  17:36:00                5.224                  0.478
...            ...       ...                  ...                    ...
2069356 2010-11-22  18:40:00                5.408                  0.150
2069357 2010-11-22  18:41:00                5.528                  0.144
2071586 2010-11-24  07:50:00                5.172                  0.050
2071587 2010-11-24  07:51:00                5.750                  0.000
2072997 2010-11-25  07:21:00                5.074                  0.240

         Voltage  Global_intensity  Sub_metering_1  Sub_metering_2  \
1         233.63              23.0             0.0             1.0
2         233.29              23.0             0.0             2.0
3         233.74              23.0             0.0             1.0
11        232.78              23.2             0.0             1.0
12        232.99              22.4             0.0             1.0
...          ...               ...             ...             ...
2069356   231.50              23.6            48.0             0.0
2069357   232.48              24.6            53.0             0.0
2071586   235.18              22.0             0.0            38.0
2071587   234.40              24.6             0.0            39.0
2072997   238.55              21.4             1.0             2.0

         Sub_metering_3
1                  16.0
2                  17.0
3                  17.0
11                 17.0
12                 16.0
...                 ...
2069356             0.0
2069357             0.0
2071586            17.0
2071587            17.0
2072997            18.0

[17381 rows x 9 columns]

Завдання 1 (з використанням NumPy)
[['16/12/2006' '17:25:00' '5.36' ... '0.0' '1.0' '16.0']
 ['16/12/2006' '17:26:00' '5.374' ... '0.0' '2.0' '17.0']
 ['16/12/2006' '17:27:00' '5.388' ... '0.0' '1.0' '17.0']
 ...
 ['24/11/2010' '07:50:00' '5.172' ... '0.0' '38.0' '17.0']
 ['24/11/2010' '07:51:00' '5.75' ... '0.0' '39.0' '17.0']
 ['25/11/2010' '07:21:00' '5.074' ... '1.0' '2.0' '18.0']]
Час виконання:
Pd: 0.012995481491088867 Np:1.0561587810516357 сек
 ------------------------------------------


Завдання 2
              Date      Time  Global_active_power  Global_reactive_power  \
4       2006-12-16  17:28:00                3.666                  0.528
5       2006-12-16  17:29:00                3.520                  0.522
6       2006-12-16  17:30:00                3.702                  0.520
7       2006-12-16  17:31:00                3.700                  0.520
14      2006-12-16  17:38:00                4.054                  0.422
...            ...       ...                  ...                    ...
2075243 2010-11-26  20:47:00                0.910                  0.000
2075244 2010-11-26  20:48:00                0.912                  0.000
2075245 2010-11-26  20:49:00                0.948                  0.000
2075246 2010-11-26  20:50:00                1.198                  0.128
2075247 2010-11-26  20:51:00                1.024                  0.106

         Voltage  Global_intensity  Sub_metering_1  Sub_metering_2  \
4         235.68              15.8             0.0             1.0
5         235.02              15.0             0.0             2.0
6         235.09              15.8             0.0             1.0
7         235.22              15.8             0.0             1.0
14        235.24              17.6             0.0             1.0
...          ...               ...             ...             ...
2075243   238.71               3.8             0.0             1.0
2075244   239.25               3.8             0.0             1.0
2075245   238.16               4.0             0.0             1.0
2075246   238.11               5.0             0.0             1.0
2075247   238.84               4.2             0.0             1.0

         Sub_metering_3
4                  17.0
5                  17.0
6                  17.0
7                  17.0
14                 17.0
...                 ...
2075243             0.0
2075244             0.0
2075245             0.0
2075246             0.0
2075247             0.0

[1378530 rows x 9 columns]

Завдання 2 (з використанням NumPy)
[235.68 235.02 235.09 ... 239.82 239.7  239.55]
Час виконання:
Pd: 0.07700109481811523 Np:0.9795384407043457 сек
 ------------------------------------------


Завдання 3
              Date      Time  Global_active_power  Global_reactive_power  \
45      2006-12-16  18:09:00                4.464                  0.136
460     2006-12-17  01:04:00                4.582                  0.258
464     2006-12-17  01:08:00                4.618                  0.104
475     2006-12-17  01:19:00                4.636                  0.140
476     2006-12-17  01:20:00                4.634                  0.152
...            ...       ...                  ...                    ...
2071589 2010-11-24  07:53:00                4.666                  0.000
2071590 2010-11-24  07:54:00                4.694                  0.000
2071591 2010-11-24  07:55:00                4.602                  0.000
2071592 2010-11-24  07:56:00                4.536                  0.000
2071593 2010-11-24  07:57:00                4.626                  0.000

         Voltage  Global_intensity  Sub_metering_1  Sub_metering_2  \
45        234.66              19.0             0.0            37.0
460       238.08              19.6             0.0            13.0
464       239.61              19.6             0.0            27.0
475       237.37              19.4             0.0            36.0
476       237.17              19.4             0.0            35.0
...          ...               ...             ...             ...
2071589   235.72              19.8             0.0            39.0
2071590   236.78              19.8             0.0            39.0
2071591   237.08              19.4             0.0            40.0
2071592   237.03              19.0             0.0            39.0
2071593   236.78              19.4             0.0            39.0

         Sub_metering_3
45                 16.0
460                 0.0
464                 0.0
475                 0.0
476                 0.0
...                 ...
2071589            17.0
2071590            18.0
2071591            17.0
2071592            17.0
2071593            17.0

[2509 rows x 9 columns]

Завдання 3 (з використанням NumPy)
[['16/12/2006' '17:34:00' '4.448' ... '0.0' '1.0' '17.0']
 ['16/12/2006' '17:48:00' '4.474' ... '0.0' '0.0' '17.0']
 ['16/12/2006' '17:57:00' '4.512' ... '0.0' '0.0' '17.0']
 ...
 ['24/11/2010' '07:55:00' '4.602' ... '0.0' '40.0' '17.0']
 ['24/11/2010' '07:56:00' '4.536' ... '0.0' '39.0' '17.0']
 ['24/11/2010' '07:57:00' '4.626' ... '0.0' '39.0' '17.0']]
[['16/12/2006' '18:04:00' '4.928' ... '0.0' '37.0' '16.0']
 ['16/12/2006' '18:05:00' '6.052' ... '0.0' '37.0' '17.0']
 ['16/12/2006' '18:06:00' '6.752' ... '0.0' '36.0' '17.0']
 ...
 ['26/11/2010' '20:49:00' '0.948' ... '0.0' '1.0' '0.0']
 ['26/11/2010' '20:50:00' '1.198' ... '0.0' '1.0' '0.0']
 ['26/11/2010' '20:51:00' '1.024' ... '0.0' '1.0' '0.0']]
Час виконання:
Pd: 0.020015716552734375 Np:5.351179122924805 сек
 ------------------------------------------


Завдання 4
Sub_metering_1    1.575086
Sub_metering_2    1.837492
Sub_metering_3    9.109592
dtype: float64

Завдання 4 (з використанням NumPy)
[1.120666 1.295606 6.46398 ]
Час виконання:
Pd: 0.14596080780029297 Np:0.833125114440918 сек
 ------------------------------------------


Завдання 5:
              Date      Time  Global_active_power  Global_reactive_power  \
41      2006-12-16  18:05:00                6.052                  0.192
44      2006-12-16  18:08:00                6.308                  0.116
17496   2006-12-28  21:00:00                6.376                  0.252
17499   2006-12-28  21:03:00                7.906                  0.286
17502   2006-12-28  21:06:00                7.184                  0.000
...            ...       ...                  ...                    ...
2066467 2010-11-20  18:31:00                6.830                  0.394
2066471 2010-11-20  18:35:00                6.784                  0.364
2066475 2010-11-20  18:39:00                6.362                  0.372
2066479 2010-11-20  18:43:00                6.324                  0.376
2066485 2010-11-20  18:49:00                6.210                  0.174

         Voltage  Global_intensity  Sub_metering_1  Sub_metering_2  \
41        232.93              26.2             0.0            37.0
44        232.25              27.0             0.0            36.0
17496     235.94              27.4             1.0            53.0
17499     235.93              33.6             1.0            73.0
17502     235.70              30.4             2.0            73.0
...          ...               ...             ...             ...
2066467   229.39              30.2            24.0            34.0
2066471   228.38              30.0            21.0            35.0
2066475   229.83              28.0            16.0            35.0
2066479   229.93              27.8            14.0            35.0
2066485   228.82              27.4            21.0            34.0

         Sub_metering_3
41                 17.0
44                 17.0
17496              17.0
17499              17.0
17502              17.0
...                 ...
2066467            16.0
2066471            16.0
2066475            16.0
2066479            17.0
2066485            17.0

[298 rows x 9 columns]

Завдання 5 (з використанням NumPy)
[['16/12/2006' '18:05:00' '6.052' ... '0.0' '37.0' '17.0']
 ['16/12/2006' '18:08:00' '6.308' ... '0.0' '36.0' '17.0']
 ['28/12/2006' '21:00:00' '6.376' ... '1.0' '53.0' '17.0']
 ...
 ['20/11/2010' '18:37:00' '6.31' ... '15.0' '35.0' '16.0']
 ['20/11/2010' '18:41:00' '6.282' ... '14.0' '35.0' '16.0']
 ['20/11/2010' '18:45:00' '6.564' ... '13.0' '40.0' '16.0']]
Час виконання:
Pd: 0.6891000270843506 Np:4.034834146499634 сек
 ------------------------------------------